import { ArrowUpRight } from 'lucide-react';
import { Reveal, RevealDetails } from '@/components/ui/Reveal';
import { SectionHeading } from '@/components/ui/SectionHeading';
import { ArrowLink } from '@/components/ui/ArrowLink';
import { WorkshopEnrollment } from '@/components/sections/WorkshopEnrollment';
import { partners } from '@/data/partners';
import { socials } from '@/data/socials';
import { site } from '@/data/site';
import { CopyCode } from '@/components/ui/CopyCode';
import { Parallax } from '@/components/ui/Parallax';

export function Mindset() { return <section id="mindset" className="mindset section-pad"><Reveal><span className="eyebrow"><i/>THE KNIGHTFX MINDSET</span><h2><span className="lime-text">DISCIPLINE</span><br/>OVER<br/><em>EMOTION.</em></h2></Reveal><Reveal delay={.12}><div className="mindset-aside"><span className="vertical-rule"/><p className="statement">Markets are uncertain.<br/>Your process doesn’t have to be.</p><p>KNIGHTFX focuses on education, structured analysis, risk awareness and disciplined execution.</p><a href="#about" className="text-link">THE PRINCIPLES <ArrowUpRight size={15}/></a></div></Reveal><span className="mindset-ghost">01</span></section>; }

export function About() { const items = [{ n:'01',t:'DISCIPLINE',d:'Develop a structured process and approach the markets with consistency.'},{n:'02',t:'STRATEGY',d:'Understand market concepts, structure, price action and trade planning.'},{n:'03',t:'GROWTH',d:'Keep improving your knowledge, execution and decision-making.'}]; return <section id="about" className="about section-pad"><SectionHeading label="ABOUT KNIGHTFX">MORE THAN<br/><em>A TRADING COMMUNITY.</em></SectionHeading><Reveal delay={0.12}><div className="about-intro"><p>KNIGHTFX TRADERS is a trading-focused brand built around education, workshops and a community-driven approach to learning.</p><span>BUILT ON PROCESS. GROUNDED IN RISK.</span></div></Reveal><div className="principle-list">{items.map((x,i)=><Reveal key={x.n} delay={0.08+i*0.09}><article className="principle-row"><span className="lime-text principle-num">{x.n}</span><h3>{x.t}</h3><p>{x.d}</p><ArrowUpRight size={18}/></article></Reveal>)}</div></section>; }

export function Offers() { const items=[['01','EDUCATION','Structured learning in Forex, Futures and XAUUSD, with focus on market structure, risk management and trading psychology.'],['02','FUTURES + CFD WORKSHOP','An intensive workshop covering both CFD and Futures markets.'],['03','WORKSHOPS','Focused practical sessions covering trading concepts and futures education.'],['04','COMMUNITY','A place to learn, discuss markets and connect with fellow traders.']]; return <section className="offers section-pad"><SectionHeading label="WHAT WE OFFER">BUILT FOR<br/><em>SERIOUS TRADERS.</em></SectionHeading><div className="offer-list">{items.map(([n,t,d],i)=><Reveal key={n} delay={i*0.09}><article className="offer-row"><span className="offer-num">{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight size={19}/></article></Reveal>)}</div></section>; }

export function Workshop() { return <section id="workshop" className="workshop section-pad"><div className="workshop-heading"><SectionHeading label="WORKSHOP">MASTER THE<br/><em>MARKETS.</em></SectionHeading><Reveal delay={0.12}><p>An intensive trading workshop covering both CFD and Futures markets, strategy, execution and risk management.</p></Reveal></div><WorkshopEnrollment/></section>; }

export function Partners() { const confirmed=partners.filter(p=>p.isPartner); return <section id="partners" className="partners section-pad"><SectionHeading label="KNIGHTFX ECOSYSTEM">PARTNERED<br/><em>WITH</em></SectionHeading><Reveal delay={0.12}><div className="partner-promo-banner"><div><span>USE CODE</span><strong>{site.promoCode}</strong><small>FOR ALL PARTNER FIRMS</small></div><CopyCode code={site.promoCode}/></div></Reveal><Reveal delay={0.18}><div className="partner-intro"><p>Trusted platforms and firms within the KNIGHTFX ecosystem.</p></div></Reveal><div className="partner-grid">{confirmed.map((p,i)=><Reveal key={p.name} className="partner-card-reveal" delay={i*0.09}><article className="partner-card"><div className="partner-card-top"><span className="partner-index">0{i+1} / 04</span><ArrowUpRight size={17}/></div><div className={`partner-logo-wrap${p.logo ? ' has-logo' : ''}`}>{p.logo && <img className="partner-logo" src={p.logo} alt={`${p.name} official logo`} />}</div><h3 className="partner-card-name">{p.name}</h3><p className="partner-description">{p.description}</p>{p.offerText && <p className="partner-offer">AVAILABLE OFFER · {p.offerText}</p>}<a className="partner-visit" href={p.url} target="_blank" rel="noopener noreferrer">VISIT FIRM <ArrowUpRight size={16}/></a></article></Reveal>)}</div><Reveal delay={0.18}><p className="disclaimer-small">Partner offers, promotional codes and program terms may change. Please verify the current terms directly with each provider before purchasing.</p></Reveal></section>; }

export function Community() { return <section id="community" className="community section-pad"><Parallax className="community-orb"/><Reveal><span className="eyebrow"><i/>TELEGRAM COMMUNITY</span></Reveal><div className="community-layout"><Reveal><h2>KNIGHT FX<br/><em>TRADERS.</em></h2></Reveal><Reveal delay={0.12}><div><p>Join the official KNIGHTFX community for trading education, market discussions and updates.</p><div className="social-links">{socials.map(s=><a key={s.label} href={s.href} target="_blank" rel="noopener noreferrer">JOIN TELEGRAM <ArrowUpRight size={15}/></a>)}</div><span className="community-disclaimer">Educational Purpose Only<br/>Not SEBI Registered</span></div></Reveal></div></section>; }

const questions=[['What is KNIGHTFX?','A trading-focused brand built around education, workshops and a community-driven approach to learning.'],['What does the Futures + CFD Workshop cover?','CFD and Futures fundamentals, market structure, price action, strategy and execution, risk management, trade planning, trading psychology, practical execution and interactive Q&A.'],['How much does the workshop cost?','The current workshop price is $150. Apply the KNIGHTFX coupon for $50 off and a final price of $100.'],['How many members can join the workshop?','The workshop is limited to 10 members.'],['How do I reserve a spot?','Message @Knightfx16 to reserve your place in the Futures + CFD Workshop.'],['How do partner offers work?','Confirmed partner offers and promo codes will be listed here. Always verify current terms with the provider.']];
export function FAQ() { return <section className="faq section-pad"><SectionHeading label="QUESTIONS, ANSWERED">CLARITY BEFORE<br/><em>COMMITMENT.</em></SectionHeading><div className="faq-list">{questions.map(([q,a],i)=><RevealDetails key={q} className="faq-item" delay={i*0.08}><summary><span className="faq-num">0{i+1}</span>{q}<span className="faq-plus"/></summary><p>{a}</p></RevealDetails>)}</div></section>; }

export function FinalCTA() { return <section className="final-cta section-pad" id="contact"><div className="final-mark">KNIGHT</div><Reveal><span className="eyebrow"><i/>YOUR NEXT MOVE STARTS WITH A PROCESS</span></Reveal><Reveal delay={0.08}><h2>MASTER<br/><em>THE PROCESS.</em></h2></Reveal><Reveal delay={0.16}><p>Discipline. Strategy. Growth.<br/>Build your process. Improve your execution. Keep learning.</p></Reveal><Reveal delay={0.24}><div className="final-actions"><ArrowLink href="#workshop">Explore the Workshop</ArrowLink></div></Reveal></section>; }

export function Footer() { const year=2026; return <footer className="footer"><Reveal><div className="footer-main"><a className="footer-brand" href="#home"><span>KNIGHTFX</span><small>TRADERS</small><i>{site.tagline}</i></a><nav aria-label="Footer navigation">{['HOME','ABOUT','WORKSHOP','PARTNERS','COMMUNITY','CONTACT'].map((x,i)=><a key={x} href={['#home','#about','#workshop','#partners','#community','#contact'][i]}>{x}</a>)}</nav><div className="footer-social">{socials.map(s=><a href={s.href} key={s.label} target="_blank" rel="noreferrer">{s.label}<ArrowUpRight size={13}/></a>)}{!socials.length&&<span>SOCIAL LINKS COMING SOON</span>}</div></div></Reveal><Reveal delay={0.1}><div className="risk-copy"><span>RISK DISCLOSURE</span><p>Trading financial markets involves substantial risk and may not be suitable for every trader. Content, market commentary and educational material provided by KNIGHTFX are for informational and educational purposes only and should not be considered financial advice or a guarantee of future results. Past performance does not guarantee future results. Always conduct your own research and consider your individual risk tolerance.</p></div></Reveal><Reveal delay={0.18}><div className="footer-bottom"><span>© {year} KNIGHTFX TRADERS</span><span>DISCIPLINE • STRATEGY • GROWTH</span><div>{site.legal.termsUrl ? <a href={site.legal.termsUrl}>TERMS</a> : <span>TERMS</span>}{site.legal.privacyUrl ? <a href={site.legal.privacyUrl}>PRIVACY</a> : <span>PRIVACY</span>}{site.legal.riskUrl ? <a href={site.legal.riskUrl}>RISK DISCLOSURE</a> : <span>RISK DISCLOSURE</span>}</div></div></Reveal></footer>; }
