import { ArrowUpRight } from 'lucide-react';
import { Reveal } from '@/components/ui/Reveal';
import { SectionHeading } from '@/components/ui/SectionHeading';
import { ArrowLink } from '@/components/ui/ArrowLink';
import { programs } from '@/data/programs';
import { partners } from '@/data/partners';
import { socials } from '@/data/socials';
import { site } from '@/data/site';
import { CopyCode } from '@/components/ui/CopyCode';
import { workshop } from '@/data/workshops';

export function Mindset() { return <section id="mindset" className="mindset section-pad"><Reveal><span className="eyebrow"><i/>THE KNIGHTFX MINDSET</span><h2><span className="lime-text">DISCIPLINE</span><br/>OVER<br/><em>EMOTION.</em></h2></Reveal><Reveal delay={.12}><div className="mindset-aside"><span className="vertical-rule"/><p className="statement">Markets are uncertain.<br/>Your process doesn’t have to be.</p><p>KNIGHTFX focuses on education, structured analysis, risk awareness and disciplined execution.</p><a href="#about" className="text-link">THE PRINCIPLES <ArrowUpRight size={15}/></a></div></Reveal><span className="mindset-ghost">01</span></section>; }

export function About() { const items = [{ n:'01',t:'DISCIPLINE',d:'Develop a structured process and approach the markets with consistency.'},{n:'02',t:'STRATEGY',d:'Understand market concepts, structure, price action and trade planning.'},{n:'03',t:'GROWTH',d:'Keep improving your knowledge, execution and decision-making.'}]; return <section id="about" className="about section-pad"><SectionHeading label="ABOUT KNIGHTFX">MORE THAN<br/><em>A TRADING COMMUNITY.</em></SectionHeading><div className="about-intro"><p>KNIGHTFX TRADERS is a trading-focused brand built around education, personal mentorship, workshops, market insights and a community-driven approach to learning.</p><span>BUILT ON PROCESS. GROUNDED IN RISK.</span></div><div className="principle-list">{items.map(x=><Reveal key={x.n}><article className="principle-row"><span className="lime-text principle-num">{x.n}</span><h3>{x.t}</h3><p>{x.d}</p><ArrowUpRight size={18}/></article></Reveal>)}</div></section>; }

export function Offers() { const items=[['01','EDUCATION','Structured learning in Forex, Futures and XAUUSD, with focus on market structure, risk management and trading psychology.'],['02','PERSONAL MENTORSHIP','Individual guidance focused on developing a more structured trading process.'],['03','WORKSHOPS','Focused practical sessions covering trading concepts and futures education.'],['04','COMMUNITY','A place to learn, discuss markets and connect with fellow traders.']]; return <section className="offers section-pad"><SectionHeading label="WHAT WE OFFER">BUILT FOR<br/><em>SERIOUS TRADERS.</em></SectionHeading><div className="offer-list">{items.map(([n,t,d])=><Reveal key={n}><article className="offer-row"><span className="offer-num">{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight size={19}/></article></Reveal>)}</div></section>; }

function ProgramTopics({ topics }: { topics: string[] }) { return <ol className="topic-list">{topics.map((t,i)=><li key={t}><span>0{i+1}</span>{t}</li>)}</ol>; }
function ProgramTelegramContact() { return <div className="program-telegram"><span>Questions or interested?</span><strong>{site.programContactUsername}</strong><a href={site.programContactUrl} target="_blank" rel="noopener noreferrer">MESSAGE ON TELEGRAM <ArrowUpRight size={14}/></a></div>; }
export function Mentorship() { const p=programs.mentorship; return <section id="mentorship" className="program program-mentor section-pad"><div className="program-topline"><span className="eyebrow"><i/>PERSONAL MENTORSHIP</span><span className="program-ref">01 — GUIDED DEVELOPMENT</span></div><div className="program-layout"><div><h2>LEARN THE<br/><em>PROCESS.</em></h2><p className="program-description">A focused mentorship experience designed around your trading journey and development.</p><div className="program-cta-row"><ArrowLink href={site.programContactUrl} external>Apply for Mentorship</ArrowLink><span>◦&nbsp; {p.availability}</span></div></div><div className="program-price"><span>PROGRAM INVESTMENT</span><strong>{p.price}</strong><i>EDUCATION • PROCESS • REVIEW</i></div></div><ProgramTopics topics={p.topics}/><ProgramTelegramContact/><div className="program-watermark">KNIGHTFX</div></section>; }
export function Workshop() { const p=programs.futures; const capacity=workshop.capacity || p.capacity; return <section id="workshop" className="workshop section-pad"><div className="workshop-orbit"/><div className="program-topline"><span className="eyebrow"><i/>FUTURES WORKSHOP</span><span className="program-ref">02 — PRACTICAL LEARNING</span></div><div className="workshop-head"><div><h2>LEARN.<br/><em>PRACTICE.</em><br/>EXECUTE.</h2><p className="program-description">An intensive workshop focused on understanding futures markets, structured execution and risk management.</p></div><div className="workshop-offer"><strong>{p.price}</strong><span className="capacity"><i/> LIMITED TO {capacity} MEMBERS</span><small>{workshop.date || 'Fixed workshop capacity'}</small><ArrowLink href={site.programContactUrl} external>Reserve your spot</ArrowLink></div></div><ProgramTopics topics={p.topics}/><ProgramTelegramContact/></section>; }

export function Partners() { const confirmed=partners.filter(p=>p.isPartner); const code=confirmed[0]?.code || 'KNIGHTFX'; return <section id="partners" className="partners section-pad"><SectionHeading label="KNIGHTFX ECOSYSTEM">PARTNERED<br/><em>WITH</em></SectionHeading><div className="partner-intro"><p>Trusted platforms and firms within the KNIGHTFX ecosystem.</p></div><div className="partner-grid">{confirmed.map((p,i)=><article key={p.name} className="partner-card"><div className="partner-card-top"><span className="partner-index">0{i+1} / 04</span><ArrowUpRight size={17}/></div><div className={`partner-logo-wrap${p.logo ? ' has-logo' : ''}`}>{p.logo && <img className="partner-logo" src={p.logo} alt={`${p.name} official logo`} />}</div><h3 className="partner-card-name">{p.name}</h3><p className="partner-description">{p.description}</p>{p.offerText && <p className="partner-offer">{p.offerText}</p>}<div className="partner-code-row"><div><span>USE CODE</span><strong>{p.code}</strong><small>PROMO CODE</small></div><CopyCode code={p.code}/></div><a className="partner-visit" href={p.url} target="_blank" rel="noopener noreferrer">VISIT FIRM <ArrowUpRight size={16}/></a></article>)}</div><div className="partner-cta"><div><span className="eyebrow"><i/>TRADE WITH OUR PARTNERS</span><p>Use code {code} where applicable.</p></div><CopyCode code={code} label={`COPY ${code}`}/></div><p className="disclaimer-small">Partner offers, promotional codes and program terms may change. Please verify the current terms directly with each provider before purchasing.</p></section>; }

export function Insights() { return <section id="insights" className="insights section-pad"><div className="insights-heading"><SectionHeading label="MARKET INSIGHTS">READ THE MARKET.<br/><em>RESPECT THE RISK.</em></SectionHeading><p>Educational analysis starts with context, not predictions. Example interface only; no live market data or trade signals.</p></div><div className="analysis-panel"><div className="analysis-top"><div><span className="eyebrow">MARKET INSIGHT / SAMPLE</span><h3>XAUUSD <small>DEMO</small></h3></div><div className="sample-stamp">SAMPLE DATA<br/>NOT A SIGNAL</div></div><div className="chart-area"><div className="chart-y"><span>2,460</span><span>2,420</span><span>2,380</span><span>2,340</span></div><svg viewBox="0 0 700 210" preserveAspectRatio="none" role="img" aria-label="Illustrative sample market chart"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#b6ff00" stopOpacity=".14"/><stop offset="1" stopColor="#b6ff00" stopOpacity="0"/></linearGradient></defs><path d="M0 165 L40 151 77 158 116 122 152 134 196 95 236 110 272 89 312 113 352 78 391 95 431 52 473 68 512 44 552 77 592 50 630 61 667 23 700 35 V210 H0z" fill="url(#fill)"/><path d="M0 165 L40 151 77 158 116 122 152 134 196 95 236 110 272 89 312 113 352 78 391 95 431 52 473 68 512 44 552 77 592 50 630 61 667 23 700 35" fill="none" stroke="#b6ff00" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg></div><div className="analysis-stats"><div><span>TIMEFRAME</span><strong>1H <small>DEMO</small></strong></div><div><span>STRUCTURE</span><strong>SAMPLE</strong></div><div><span>BIAS</span><strong>SAMPLE</strong></div><span className="demo-label">ILLUSTRATIVE ONLY</span></div></div><div className="insight-cta"><ArrowLink href="#insights" variant="outline" disabled>View Market Insights</ArrowLink><span>DETAILS COMING SOON</span></div></section>; }

export function Community() { return <section id="community" className="community section-pad"><div className="community-orb"/><span className="eyebrow"><i/>TELEGRAM COMMUNITY</span><div className="community-layout"><h2>KNIGHT FX<br/><em>TRADERS.</em></h2><div><p>Join the official KNIGHTFX community for trading education, market discussions and updates.</p><div className="social-links">{socials.map(s=><a key={s.label} href={s.href} target="_blank" rel="noopener noreferrer">JOIN TELEGRAM <ArrowUpRight size={15}/></a>)}</div><span className="community-disclaimer">Educational Purpose Only<br/>Not SEBI Registered</span></div></div></section>; }

const questions=[['What is KNIGHTFX?','A trading-focused brand built around education, personal mentorship, workshops, market insights and a community-driven approach to learning.'],['What does Personal Mentorship include?','Market fundamentals, market structure, strategy development, trade execution, risk management, trading psychology, journaling and review.'],['How much does Personal Mentorship cost?','The listed program investment is $250. Mentorship registration details are coming soon.'],['What is included in the Futures Workshop?','Futures fundamentals, market structure, strategy and execution, risk management, trade planning and interactive Q&A.'],['How many members can join the Futures Workshop?','The workshop capacity is 10 members.'],['How do I register?','Registration details are coming soon. Use the contact section for future updates.'],['How do partner offers work?','Confirmed partner offers and promo codes will be listed here. Always verify current terms with the provider.'],['Where can I find KNIGHTFX market insights?','Market insight links are coming soon. Any sample interface on this site is illustrative and is not a trade signal.']];
export function FAQ() { return <section className="faq section-pad"><SectionHeading label="QUESTIONS, ANSWERED">CLARITY BEFORE<br/><em>COMMITMENT.</em></SectionHeading><div className="faq-list">{questions.map(([q,a],i)=><details key={q} className="faq-item"><summary><span className="faq-num">0{i+1}</span>{q}<span className="faq-plus"/></summary><p>{a}</p></details>)}</div></section>; }

export function FinalCTA() { return <section className="final-cta section-pad" id="contact"><div className="final-mark">KNIGHT</div><span className="eyebrow"><i/>YOUR NEXT MOVE STARTS WITH A PROCESS</span><h2>MASTER<br/><em>THE PROCESS.</em></h2><p>Discipline. Strategy. Growth.<br/>Build your process. Improve your execution. Keep learning.</p><div className="final-actions"><ArrowLink href={site.programContactUrl} external>Apply for Mentorship</ArrowLink><ArrowLink href={site.programContactUrl} variant="outline" external>Reserve Workshop Spot</ArrowLink></div></section>; }

export function Footer() { const year=2026; return <footer className="footer"><div className="footer-main"><a className="footer-brand" href="#home"><span>KNIGHTFX</span><small>TRADERS</small><i>{site.tagline}</i></a><nav aria-label="Footer navigation">{['HOME','ABOUT','MENTORSHIP','WORKSHOP','PARTNERS','COMMUNITY','CONTACT'].map((x,i)=><a key={x} href={['#home','#about','#mentorship','#workshop','#partners','#community','#contact'][i]}>{x}</a>)}</nav><div className="footer-social">{socials.map(s=><a href={s.href} key={s.label} target="_blank" rel="noreferrer">{s.label}<ArrowUpRight size={13}/></a>)}{!socials.length&&<span>SOCIAL LINKS COMING SOON</span>}</div></div><div className="risk-copy"><span>RISK DISCLOSURE</span><p>Trading financial markets involves substantial risk and may not be suitable for every trader. Content, market commentary and educational material provided by KNIGHTFX are for informational and educational purposes only and should not be considered financial advice or a guarantee of future results. Past performance does not guarantee future results. Always conduct your own research and consider your individual risk tolerance.</p></div><div className="footer-bottom"><span>© {year} KNIGHTFX TRADERS</span><span>DISCIPLINE • STRATEGY • GROWTH</span><div>{site.legal.termsUrl ? <a href={site.legal.termsUrl}>TERMS</a> : <span>TERMS</span>}{site.legal.privacyUrl ? <a href={site.legal.privacyUrl}>PRIVACY</a> : <span>PRIVACY</span>}{site.legal.riskUrl ? <a href={site.legal.riskUrl}>RISK DISCLOSURE</a> : <span>RISK DISCLOSURE</span>}</div></div></footer>; }
